version: "3.8"
services:
  springboot-app:
    image: student-management-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"   # Debug port exposed
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/feesDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
      JAVA_TOOL_OPTIONS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: feesDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"   # host:container
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
