server:
  port: 8080

spring:
  application:
    name: StudentManagementProject

  datasource:
    url: jdbc:postgresql://postgres:5432/feesDb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false